services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/
            - /etc/letsencrypt:/etc/letsencrypt:ro
        depends_on:
            - php

    php:
        build: ./docker/php
        volumes:
            - ./src:/var/www/
        depends_on:
            - redis

    redis:
        image: redis:latest
        ports:
            - "6379:6379"