services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/
            - /etc/letsencrypt:/etc/letsencrypt:ro
        depends_on:
            - php

    php:
        build: ./docker/php
        volumes:
            - ./src:/var/www/
        environment:
            - TZ=Asia/Tokyo
            - AWS_DEFAULT_REGION=ap-northeast-1
            - AWS_BUCKET=rese-bucket-s3
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - REDIS_PASSWORD=null
            - REDIS_CLIENT=phpredis
        depends_on:
            - redis

    redis:
        image: redis:latest
        ports:
            - "6379:6379"
